name: format-lint

on: [push]

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: setup
        run: |
          python -m pip install --upgrade pip
          make setup
      - name: formatting
        run: make format
      - name: linting
        run: make lint

